version: "3"

services:
  app:
    container_name: "service"
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    ports:
      - "54234:54234"
      - "55238:55238"
    depends_on:
      - postgres
      - rabbitmq
      - migrate

  postgres:
    container_name: "postgres"
    image: bitnami/postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=calendar

  migrate:
    container_name: "migrate"
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ../migrations:/migrations
    command:
      ["-path", "/migrations", "-database", "postgres://postgres:postgres@postgres:5432/calendar?sslmode=disable", "up"]
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"

