logger:
  level: 0
  encoding: "console"
  output:
    - "stdout"
    - "logger_logs.log"
rpcserver:
  host: "localhost"
  port: 54232
httpserver:
  host: "192.168.31.189"
  port: 55234
database:
  implementation: "sql"
  type: "postgres"
  dsn: "host=localhost port=5432 user=postgres password=postgres dbname=calendar sslmode=disable"